### ISSUE TITLE
"Please wait" cursor while trying to select input file makes me nervous

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1092]
Currently, when I choose `File -> Open Data Set`, the cursor changes from "arrow" to "spinning circle" (usually used to indicate that something is busy). That is not the cursor that I expect to see when I am trying to choose a file. It makes me nervous, as I thought I might have accidentally opened a giant file that is eating up my memory.

**Comment by astrofrog** [comment]
Does this happen before you've even selected any dataset? Very strange!

**Comment by pllim** [comment]
Yes. The cursor changes as soon as the file dialog pops up and only change back when a file is selected and opened.

**Comment by astrofrog** [comment]
Is this also on Linux?

**Comment by pllim** [comment]
Yes, the very same. Qt4.

**Comment by astrofrog** [comment]
I think the culprit is:

```
    @set_cursor(Qt.WaitCursor)
```

which appears in ``data_wizard.py`` (the same happens for loading/saving sessions in ``glue/app/qt/application.py``.

I think the correct solution should be to change the cursor only when actually loading the file, inside of those functions. The best solution would be to make a context manager version of the ``set_cursor`` function and use it for the code that actually does the loading in ``load_data``.

@pllim - would you have time to try and do a PR for this to see if you can fix it?

**Comment by pllim** [comment]
See potential fix in #1097.
