### ISSUE TITLE
Why does Glue not use relative import?

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1105]
Just wondering.

**Comment by astrofrog** [comment]
It used to, but I changed to absolute imports when I did a big refactor recently - the reason is two-fold - there are a lot of cross-package imports that ended up looking like `` from .....utils`` which became unreadable. The other reason is that moving forward, each component of glue should end up being very modular and ideally a plugin, and we need to be able to move them around if needed within the package or out into separate packages (or vice-versa, from outside to in the package). Relative imports are just a mess for this.

Note that we still use relative imports for tests because they are expected to always live in the same place compared to the code they test.

**Comment by pllim** [comment]
Ah, okay. Thanks for the clarifications. I almost changed the imports back to relative!
