### ISSUE TITLE
Table viewer can be improved

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1132]
Desired improvements:

- [x] Display column units. (#1135)
- [x] ~~Row number should start from 1 (display-wise, row 0 does not make sense).~~

On an unrelated note, this is what Google gives me when I searched for "glue table viewer" :joy: :
![screenshot](https://cloud.githubusercontent.com/assets/2090236/18881543/ba8618f4-84a9-11e6-879c-c6dfca18fb88.png)

**Comment by astrofrog** [comment]
@pllim - both changes sound sensible! Let me know if you want to work on either, otherwise I will.

**Comment by pllim** [comment]
I am not familiar with Glue framework. Probably much faster if you do.

**Comment by astrofrog** [comment]
@pllim - I added support for units in #1135. For the row index, after thinking about this a bit, I would like to leave it as is. My reasoning is as follows: the only reason we would want to show the row numbers is because they could be used by users to access that data index via the terminal - there's not much point showing them otherwise. Note that if you sort the table, the numbers are no longer in order - they truly are the index of the data, not the row in the visual table. Does this make sense?

**Comment by pllim** [comment]
Thanks, @astrofrog ! Yes, I see that you already have the indices in the current viewer, so that is fine.

**Comment by astrofrog** [comment]
(#1135 is now merged)

**Comment by pllim** [comment]
Thanks! :star2: :frog:
