### ISSUE TITLE
Weird image viewer behavior with JWST workshop IFU cube

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#1166]
This is using `data/IFU_datasets/NIRSpec_Simulated/JWST-NIRSpec-IFU-GAL2136_CLEAR_PRISM.fits` from JWST Data Analysis Workshop II.

1. The image viewer axis labels are `Spatial_X` and `Spatial_X`, even when I specify `x vs y` (see screenshot). Not sure if the WCS is messed up, or it is a Glue bug.
2. The value displayed in `m` text box for the `slice` part is:
    a. Confusing: The "4." is cut off on the left.
    b. Wrong: This is JWST data, so I am expecting a slice to be in the order of micron, not meter, but I don't see any exponent in the text box. Not sure if the WCS is messed up or it is a Glue bug.

<img width="465" alt="untitled" src="https://cloud.githubusercontent.com/assets/2090236/20186296/6b5235b8-a73d-11e6-89be-d373c4d1f71f.png">

**Comment by astrofrog** [comment]
The fact that the unit is given in m is an astropy.wcs 'issue' (design) which causes units to be converted when the WCS is parsed. There's unfortunately not much we can do without changing this behavior in astropy. The values were also being truncated at the time so that may have contributed to the issue. I think the other issues you mention should be fixed, but please feel free to re-open if any of these issues remain.

Once glue v0.11 is
