### ISSUE TITLE
crazy idea for state handling 

### ISSUE THREAD

**Issue by ChrisBeaumont** [glue-viz/glue#775]
This is a pretty speculative / potentially unfeasible idea, but:

I've been playing around with react lately (facebook's library for building UIs in javascript). They have a nice philosophy for keeping UI's in proper sync. Each UI component implements a render() method that _completely_ configures the UI from scratch, based on the component's state. React then autodetects all state changes and calls render() as appropriate. 

Now, react has lots of internal fanciness that makes this efficient (the render method manipulates a mock UI where all method calls are cheap, and react converts that into an efficient, minimal set of real DOM manipulations. Figuring out how to do that with Qt could be really tricky). But it avoids a whole class of buts that Glue repeatedly encounters -- namely, we forget to attach the appropriate event listener to update a widget when state changes in some unforeseen way. It's a really nice pattern to have render() be the single place that renders the UI based on the current state, and relying on a separate system to run render when appropriate. 

It might be worth thinking about whether it's possible to nudge glue in this direction -- maintaining a more formal UI state datastructure, organizing display logic around correctly representing this state, and having a more generic (glue-agnostic) system determine when components need to be re-displayed. One concrete sign that we're moving in this direction is that most Qt connect() and emit() calls would be consolidated in one place, and _not_ in GlueApplication, ScatterWidget, ScatterClient, etc. All of that code would be focused solely on manipulating state and how to render that state (the widget classes would still use connect() to tie user input like mouseclicks to state manipulation, but they would not be directly connecting state change events to GUI update handlers -- that logic would be more generally handled elsewhere)

**Comment by astrofrog** [comment]
This is a very interesting idea - just this week, while digging through #755 and #772, I've run into a maze of connections/callbacks which is getting pretty complex, so any way to simplify that would be nice.

So if I understand correctly, all UI components would then store their state in the same way - that it, just as an example, they would all store the state information in a particular attribute? If so, then I assume that the most efficient way to detect state changes would be to actually make the state object able to tell the main application when its state has changed? (rather than having the main application check through all the states).

Having everything determined by state then also makes it trivial to implement undo/redo and saving (it's already simple at the moment, but this would somehow formalize it and could provide it for free for *any* widget).

I guess that having this separation of state and UI then also would make it a lot easier to switch UI framework in future if needed.

So if I understand correctly, we'd still have callbacks etc but these would all live in GlueApplication as you said - but just to be clear, how would we then handle plugins? Would plugins then provide a function containing all the emit/connect calls, in addition to the widget?

(sorry, just thinking out loud - I think it would be great to formalize things in this way!)

**Comment by ChrisBeaumont** [comment]
>  just as an example, they would all store the state information in a particular attribute?

yes. For example in react a ui component is fully specified by `props` (which is frozen at init time and never changes) and `state` (allowed to change). In Glue `state` could be a `CallbackProperty` so that it automatically notifies about change events.

Another interesting pattern in react apps is the use of immutable versions of dicts,lists,etc (eg https://github.com/tobgu/pyrsistent) to store state. that makes it easy to detect when state **hasn't** changed, since `id(old) == id(new)` guarantees the contents are the same. So if you have a big state tree (UIs are usually hierarchical) and only change one segment is modified, you walk the tree and quickly skip updates on the unmodified parts).

> trivial to implement undo/redo and saving

right -- saving amounts to serializing a tree of (component, props, state)

>  we'd still have callbacks... how would we then handle plugins?

core widgets and plugins would define event code similarly -- they would have an opportunity to attach callbacks to click/key/move events. However, these callbacks would *not* directly manipulate widgets, they would only make state modifications. So plugins would provide:
  * Logic that configures a widget based on it's own state (and that of the parent viewer / application / etc)
  * An entrypoint to attach callback functions to UI events, which modify state
  * (maybe) the ability to export their own state, if other plugins are meant to interact with them

Anyways, the central idea is that you focus more on the UI state, how to convert `state->display`, and how to convert `user actions -> state change`. `WidgetProperties` were also trying to get at this idea, I now realize (scatter plot code manipulates a piece of state like `self.xlog = True`, and a more generic piece of code says "when I draw a checkbox, make it checked if my state is True". But even with widget properties, data viewers have to attach more callbacks than is ideal (eg ScatterWidget has to call  `connect_bool_button` to link part of it's state to part of its UI, which is brittle as you've seen). Fundamentally if we have an authoritative chunk of state and a collection of render() methods that know how to display the correct widgets given that state, then we *should* be able to rely on a more generic system to keep the UI in sync at all times.

**Comment by astrofrog** [comment]
I've been thinking about this and tinkering with ideas while traveling. There are a few open questions that we should think about:

- At the moment, matplotlib visualizations are implemented on the client side, not the widget side, but I think that in the above paradigm, this would need to change. Matplotlib would be treated as being something that interprets and renders the state, and this would make it easier to change plotting framework in future. This is a reasonably large change.

- One thing to consider is how granular we go with state/render. We could for example have one state object per data viewer (with sub-attributes). There would then be one render method per data viewer widget, and this one could choose to either just re-render everything, or re-render specific elements, depending on what has changed. On the other hand, we could have a state/render pair for each UI element (one combo box, one button, etc.) but this means that we then still need to have many connect calls to connect each given state to its corresponding render. So I think it may be cleaner to have one state object per data viewer. Of course, the state object could still have a mechanism to indicate which sub-parts of the state have changed, so that the widget could do e.g. (pseudo-code):

```
if state.label.changed:
    self.ui.label.setText(state.label)
```

inside the ``render`` method.

All this can be tested with a single viewer without changing the rest of glue. I can develop an example plugin that tries to implement this paradigm, even if the rest of glue does not change.

**Comment by ChrisBeaumont** [comment]
> One thing to consider is how granular we go with state/render.

Yeah, I think maximum hierarchy here is the key -- most render methods would probably be largely a loop over child components, calling render on each. 

> but this means that we then still need to have many connect calls to connect each given state to its corresponding render

This might be the trickiest part (react for example uses a single global event dispatcher to listen to mouse clicks, which is a very different paradigm than qt event signals/slots). From a complexity standpoint, I think the critical factor is not how many raw signal handlers are used, but rather how *automatically* these signals can be defined. Forcing the user to manually stitch together event handlers in the correct sequence has proven error prone for us in the past. But if the proper sequence was inferred by a central system that introspects a data viewer, we could afford more complexity in terms of low-level signal/slot logic (since that's hidden from the data viewer developer).

**Comment by astrofrog** [comment]
I'm going to close this, as we now do have an infrastructure for state classes, at least for the viewers, and this did make things a lot cleaner!
