### ISSUE TITLE
Issue with linking derived components

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#909]
Linking derived components via the GUI currently does not work. The following example replicates what happens when using the GUI:

``` python
from glue.core.component_link import ComponentLink
from glue.core import Data, DataCollection
from glue.core.component_id import ComponentID
from glue.core.parse import ParsedCommand, ParsedComponentLink

data1 = Data(x=[1,2,3,4,5], y=[1,2,3,4,5], label='data1')
data2 = Data(a=[1,2,3,4,5], b=[1,2,3,4,5], label='data2')

dc = DataCollection([data1, data2])

labels = {'data2:a': data2.id['a'], 'data2:b': data2.id['b']}
pc = ParsedCommand("{data2:a} - {data2:b}", labels)
new_id = ComponentID('color')
link2 = ParsedComponentLink(new_id, pc)
data2.add_component_link(link2)

link4 = ComponentLink([data1.id['x']], data2.id['a'])

dc.add_link(link4)

print(data2['color'])
```

The error is:

``` python
Traceback (most recent call last):
  File "simple.py", line 21, in <module>
    print(data2['color'])
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/data.py", line 628, in __getitem__
    result = comp.data
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/component.py", line 240, in data
    return self._link.compute(self._data)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/parse.py", line 180, in compute
    return self._parsed.evaluate(data, view)
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/parse.py", line 147, in evaluate
    return eval(cmd, vars(env), locals())  # careful!
  File "<string>", line 1, in <module>
  File "/Users/tom/Dropbox/Code/development/glue-viz/glue/glue/core/data.py", line 619, in __getitem__
    raise IncompatibleAttribute(key)
glue.core.exceptions.IncompatibleAttribute: a
```

What's happening here is that the derived component is permanently referred to by the string `"{data2:a} - {data2:b}"`. Furthermore, when doing the linking of the single component with `ComponentLink([data1.id['x']], data2.id['a'])`, `a` is replaced by `x` in `data2`, so the parsed command no longer works.

It's not clear what the best way to deal with this would be, but another question that comes up here is whether we should actually be replacing component IDs upon linking at all (I find this to be counter-intuitive and it causes issues as shown here)

@ChrisBeaumont - do you have any thoughts here?

**Comment by ChrisBeaumont** [comment]
>  another question that comes up here is whether we should actually be replacing component IDs upon linking at all 

Yeah this has never worked very well. Here's my recollection of the history:

Initially when you said that D1.x and D2.y were the same, then we would add a derived components for D1.y and D2.x. This was annoying from a UI perspective, since in practice these 2 components already had similar / identical names (like "RA J2000"), and so widgets that listed all of a dataset's components would show duplicated/near-duplicated entries. We've tried a bunch of strategies for dealing with this, but the current one is to remove one of the componentIDs and replace it with another. 

I think our general system of "arbitrary web of linked components" might be too general + confusing. I wonder if there's a better UI that lets you, for example, glue components to common "standard" entities, so that links look less like connections directly between datasets and more like a hub-spoke model where components derive from a central registry.

**Comment by astrofrog** [comment]
This works properly now that the linking infrastructure has been somewhat refactored
