### ISSUE TITLE
3D rendering needs better default color

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#922]
Grey on black background is not very visible. May I suggest lime green and max opacity (alpha)?

**Comment by astrofrog** [comment]
@pllim - we should indeed change to max opacity. I have included a fix in glue 0.7.1 that makes the shade of grey brighter. The issue is that at the moment, the data color in shared by all viewers and has to work on black and white backgrounds. The ideal solution would be to make it so that the default data color can be background-color-aware.

In any case, with glue 0.7.1, the only additional fix needed in the short term is making the opacity default to 100%. The relevant repository to change the alpha is https://github.com/glue-viz/glue-3d-viewer - if you don't have time to do this in the next few days, I can make the change (or anyone else reading this issue is welcome to).

**Comment by astrofrog** [comment]
This should be better now
